#!/bin/bash

nr=$1
day="day${nr}"
cp -r ./template "./$day"
cd "./$day"
sed -i '' "s|testday|$day|g" Cargo.toml
mv "./src/bin/dayxx_part1.rs"  "./src/bin/day${nr}_part1.rs"
mv "./src/bin/dayxx_part2.rs"  "./src/bin/day${nr}_part2.rs"
